export const USER_COLLECTION = 'users'
export const PRODUCTS_SUBCOLLECTION = 'product'
export const ORDER_SUBCOLLECTION = 'order'
export const ORDER_DETAIL_SUBCOLLECTION = 'orderDetail'
export const ORDER_ID = 'orderId'
